name: MinigamesLib2
main: com.github.mce.minigames.impl.MinigamesPlugin
version: ${minigames.releaseversion}-${minigames.timestamp}
author: [InstanceLabs, MysticCity, MasteroftheHell, TheMrQuake, mepeisen]
softdepend: [Vault]
commands:
   mg2:
      description: Main command for minigames lib version 2
      usage: /mg2 [action]
