name: MinigamesLib
main: com.comze_instancelabs.minigamesapi.MinigamesAPI
version: 1.14.8
author: [InstanceLabs, MysticCity, MasteroftheHell, TheMrQuake, mepeisen]
softdepend: [Vault]
commands:
   mapi:
      description: Main command
      usage: /mapi [action]
      aliases: [mgapi, mglib]
   party:
      description: Main Party command
      usage: /party [action]
   start:
      description: Start shortcut
      usage: /start [action]
      aliases: [startmg, startminigame]
